# Generated by Django 5.0.1 on 2025-09-23 16:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('summary', models.TextField(max_length=500, verbose_name='Resumo')),
                ('content', models.TextField(verbose_name='Conteúdo')),
                ('source', models.CharField(max_length=100, verbose_name='Fonte')),
                ('source_url', models.URLField(blank=True, verbose_name='URL da Fonte')),
                ('image_url', models.URLField(blank=True, verbose_name='URL da Imagem')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publicado')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destaque')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Publicado em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('ai_summary', models.TextField(blank=True, verbose_name='Resumo IA')),
                ('sentiment_score', models.FloatField(blank=True, null=True, verbose_name='Score de Sentimento')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='news.category', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Notícia',
                'verbose_name_plural': 'Notícias',
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['-published_at'], name='news_news_publish_ad4867_idx'), models.Index(fields=['category', '-published_at'], name='news_news_categor_5d2cdf_idx'), models.Index(fields=['is_published', '-published_at'], name='news_news_is_publ_dcad2b_idx')],
            },
        ),
    ]
